
  name: Run unit tests

  on: [push]

  jobs: 
    run-unit-tests:
      
        name: Run unit tests
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - uses: actions/setup-node@v2
            with:
              node-version: 18
              cache: 'yarn'
          
          - run: yarn install 
          - run: yarn test
